exe:
	/cluster/home/chenwq/research/rvm/gcc/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g mobilenetv2.c -o mobilenetv2 -O2 -lm -static
	# /cluster/home/chenwq/research/rvm/gcc/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g mobilenetv2_2.c -o mobilenetv2_2 -O2 -lm -static